### ISSUE TITLE
Incompatible with Ansible 2

### ISSUE THREAD

**Issue by ctreatma** [silpion/ansible-java#22]
Ansible 2 uses a different architecture for plugins and is not backwards-compatible with earlier Ansible plugins.  When we attempt to upgrade Ansible for projects that use this role, we get an exception from
[the keystore plugin](https://github.com/silpion/ansible-java/blob/next/action_plugins/keystore.py#L7) because Ansible 2 no longer defines a `runner.return_data` module.

    Unexpected Exception: No module named runner.return_data
       the full traceback was:

       Traceback (most recent call last):
         File "/usr/bin/ansible-playbook", line 85, in <module>
           sys.exit(cli.run())
         File "/usr/lib/pymodules/python2.7/ansible/cli/playbook.py", line 150, in run
           results = pbex.run()
         File "/usr/lib/pymodules/python2.7/ansible/executor/playbook_executor.py", line 148, in run
           result = self._tqm.run(play=play)
         File "/usr/lib/pymodules/python2.7/ansible/executor/task_queue_manager.py", line 237, in run
           play_return = strategy.run(iterator, play_context)
         File "/usr/lib/pymodules/python2.7/ansible/plugins/strategy/linear.py", line 195, in run
           action = action_loader.get(task.action, class_only=True)
         File "/usr/lib/pymodules/python2.7/ansible/plugins/__init__.py", line 326, in get
           self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
         File "/usr/lib/pymodules/python2.7/ansible/plugins/__init__.py", line 313, in _load_module_source
           module = imp.load_source(name, path, module_file)
         File "/tmp/kitchen/roles/groover.java/action_plugins/keystore.py", line 7, in <module>
           from ansible.runner.return_data import ReturnData
       ImportError: No module named runner.return_data```

**Comment by spul** [comment]
Currently working on it. Will take some time, but we are in general aiming for complete v2 compatibility and will release all of our public roles soon.

**Comment by spul** [comment]
Fixed with [2.0.1][1].

[1]: https://github.com/silpion/ansible-java/tree/2.0.1
