### ISSUE TITLE
Issue with keystore in Ansible 2.1.0.0

### ISSUE THREAD

**Issue by nmische** [silpion/ansible-java#28]
I get the following error when trying to use the keystore command with Ansible 2.1.0.0.
```
       Traceback (most recent call last):
         File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
           res = self._execute()
         File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 446, in _execute
           result = self._handler.run(task_vars=variables)
         File "/tmp/kitchen/roles/groover.java/action_plugins/keystore.py", line 32, in run
           tmp = self._make_tmp_path()
       TypeError: _make_tmp_path() takes exactly 2 arguments (1 given)
```

**Comment by spul** [comment]
HI, I've created an issue in our internal issue tracker and have a look at it next week.
